#!/usr/bin/env python

# General
import os
import argparse
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')
import gc
import logging
# Data Handling
import pandas as pd
import numpy as np
# Analysis
import MDAnalysis as mda
from MDAnalysis.analysis import dihedrals
from MDAnalysis import transformations
from MDAnalysis.analysis import align
from MDAnalysis.analysis import rms
from MDAnalysis.analysis import dssp
import pyKVFinder
import prolif as plf
import freesasa
from mdakit_sasa.analysis.sasaanalysis import SASAAnalysis
from tqdm.auto import tqdm
freesasa.setVerbosity(freesasa.nowarnings)

# --- Module-level Constants ---

# Chi-1 CG atom varies by residue type.
# Valid for ARG, TRP, TYR, PHE, HIS, LYS, etc. via CHI1_DEFAULT_CG.
# Branched residues and heteroatom-terminated ones are listed explicitly.
CHI1_CG_MAP = {
    'VAL': 'CG1',
    'ILE': 'CG1',
    'THR': 'OG1',
    'SER': 'OG',
    'CYS': 'SG',
}
CHI1_DEFAULT_CG = 'CG'

# Shared interaction set used by both intra- and intermolecular ProLIF runs.
# Defined once here to avoid silent divergence between the two modes.
PROLIF_INTERACTIONS = [
    "VdWContact", "HBDonor", "HBAcceptor",
    "PiStacking", "EdgeToFace", "FaceToFace",
    "Anionic", "Cationic", "CationPi"
]

DEFAULT_DOMAINS = {
    "AT1R": {
        'N-Term': (1, 14),   'TM1': (15, 45),   'ICL1': (46, 51),
        'TM2': (52, 79),     'ECL1': (80, 87),   'TM3': (88, 121),
        'ICL2': (122, 131),  'TM4': (132, 156),  'ECL2': (157, 179),
        'TM5': (180, 219),   'ICL3': (220, 226), 'TM6': (227, 257),
        'ECL3': (258, 263),  'TM7': (264, 291),  'Helix8': (292, 308),
        'C-Term': (309, 310)
    },
    "AT2R": {
        'N-Term': (1, 6),    'TM1': (7, 37),     'ICL1': (38, 43),
        'TM2': (44, 71),     'ECL1': (72, 78),   'TM3': (79, 113),
        'ICL2': (114, 122),  'TM4': (123, 147),  'ECL2': (148, 166),
        'TM5': (167, 207),   'ICL3': (208, 213), 'TM6': (214, 250),
        'ECL3': (251, 255),  'TM7': (256, 278),  'Turn/H8a': (279, 290),
        'Helix8': (291, 300),'C-Term': (301, 306)
    },
    "MAS1": {
        'N-Term': (1, 3),    'TM1': (4, 31),     'ICL1': (32, 34),
        'TM2': (35, 66),     'ECL1': (67, 71),   'TM3': (72, 105),
        'ICL2': (106, 117),  'TM4': (118, 139),  'ECL2': (140, 150),
        'TM5': (151, 187),   'ICL3': (188, 195), 'TM6': (196, 213),
        'ECL3': (214, 228),  'TM7': (229, 251),  'C-Term': (252, 253)
    }
}

CUSTOM_HELP_TEXT = """
================================================================================
                        GPCR MD ANALYSIS PIPELINE
================================================================================

Usage: python GPCR_Analysis.py --system [SYSTEM_NAME] --length [NUM] [FLAGS]

EXPECTED FOLDER SCHEME:
  [SYSTEM_NAME]/             <-- Passed via --system (e.g., AT1R)
  │
  ├── [COMPLEX_1]/           <-- e.g., A18, CONTROL
  │   ├── topology.prmtop    <-- Must contain exactly one .prmtop file
  │   ├── rep1.nc            <-- Trajectory files (.nc)
  │   └── rep2.nc
  │
  ├── [COMPLEX_2]/           <-- e.g., A19
  │   ├── topology.prmtop
  │   └── rep1.nc
  │
  └── DATA/                  <-- Auto-generated by the script for outputs
      ├── [COMPLEX_1]/
      └── [COMPLEX_2]/

CORE ARGUMENTS:
  --system         System name identifier (e.g., 'AT1R')
  --length         Receptor residue count (defines where the ligand starts)
  --system-complex Restrict run to a specific subfolder (e.g., 'A18')

ANALYSIS FLAGS (If none provided, defaults to RMSD, RMSF, DSSP):
  --RMSD           Run RMSD analysis
  --RMSF           Run RMSF analysis
  --DSSP           Run secondary structure content analysis
  --dihedrals      Run micro-switch Chi-1 dihedral analysis
  --sasa           Residue IDs for pocket SASA (e.g., --sasa 31 34 36)
  --volume         Run pyKVFinder cavity volume (falls back to --sasa residues)
  --intra          Run intra-molecular ProLIF on the whole receptor
  --intra-sel      Residue IDs for localized intramolecular ProLIF
  --inter          Run intermolecular (Protein–Ligand) ProLIF

ADVANCED / OVERRIDES:
  --custom-domains Path to a domain definition file (e.g., CUSTOM_DOMAINS.txt)
  --n-jobs         Parallel jobs for ProLIF analysis (default: 4)
  --motif-all      Provide all 3 motif resids: DRY TSWITCH NPY
================================================================================
"""

# =============================================================================
# Helper / Patch
# =============================================================================

def patch_prolif_intramolecular(fp):
    """
    Patches a ProLIF fingerprint object to ignore self-interactions (i == j),
    preventing distance-calculation crashes during intramolecular analysis.
    Uses a factory function to correctly capture each iteration's value.
    """
    for name, interaction_func in fp.interactions.items():
        def make_safe_interaction(orig_func):
            def safe_interaction(lig_res, prot_res, **kwargs):
                if lig_res.resid == prot_res.resid:
                    return None
                return orig_func(lig_res, prot_res, **kwargs)
            return safe_interaction
        fp.interactions[name] = make_safe_interaction(interaction_func)
    return fp


# =============================================================================
# Analysis Functions
# =============================================================================

def run_rmsd(u, protein_sel, ligand_sel, system_name, top, traj_list, out_dir):
    logging.info(f"Calculating RMSD for {system_name}...")

    ref = mda.Universe(top, traj_list[0])
    prot_mask = f"{protein_sel} and name CA"
    group_sels = []

    if ligand_sel:
        group_sels.append(f"{ligand_sel} and not name H*")

    R = rms.RMSD(u, ref, select=prot_mask, groupselections=group_sels)
    R.run()

    data_dict = {
        'Frame':        R.results.rmsd[:, 0],
        'Time_ps':      R.results.rmsd[:, 1],
        'Time_ns':      R.results.rmsd[:, 1] / 1000,
        'Protein_RMSD': R.results.rmsd[:, 2]
    }
    if ligand_sel:
        data_dict['Ligand_RMSD'] = R.results.rmsd[:, 3]

    pd.DataFrame(data_dict).to_csv(out_dir / f'{system_name}_RMSD_Data.csv', index=False)


def run_rmsf(u, protein_sel, ligand_sel, system_name, top, traj_list, out_dir):
    logging.info(f"Calculating RMSF for {system_name}...")

    # ref = mda.Universe(top, traj_list[0])
    # align_mask = f'{protein_sel} and name CA'
    #
    # # NOTE: in_memory=True permanently modifies u (i.e. u_concat) in place.
    # # All analyses queued after RMSF will run on the aligned trajectory.
    # # Ensure RMSD is queued before RMSF so it operates on the raw coordinates.
    # align.AlignTraj(u, ref, select=align_mask, in_memory=True).run()

    calc_masks = {'Receptor': f'{protein_sel} and name CA'}
    if ligand_sel:
        calc_masks['Ligand'] = f'{ligand_sel} and not name H*'

    rmsf_results = {}
    for target_name, mask_string in calc_masks.items():
        target_atoms = u.select_atoms(mask_string)
        rmsf_calc = rms.RMSF(target_atoms).run()
        df_target = pd.DataFrame({
            'Residue': target_atoms.resids,
            'RMSF_Å':  rmsf_calc.rmsf
        }).set_index('Residue')
        rmsf_results[target_name] = df_target

    df_rmsf_protein = rmsf_results['Receptor']
    df_rmsf_ligand  = rmsf_results.get('Ligand', None)

    df_rmsf_protein.to_csv(out_dir / f"{system_name}_Receptor_RMSF_Data.csv")
    if ligand_sel:
        df_rmsf_ligand.to_csv(out_dir / f"{system_name}_Ligand_RMSF_Data.csv")

    threshold = 1.5
    df_high_mob_receptor = df_rmsf_protein[df_rmsf_protein['RMSF_Å'] >= threshold].copy()
    if not df_high_mob_receptor.empty:
        df_high_mob_receptor.to_csv(out_dir / f"{system_name}_Receptor_HighMobRes.csv", index=True)

    if ligand_sel:
        df_high_mob_ligand = df_rmsf_ligand[df_rmsf_ligand['RMSF_Å'] >= threshold].copy()
        if not df_high_mob_ligand.empty:
            df_high_mob_ligand.to_csv(out_dir / f"{system_name}_Ligand_HighMobRes.csv", index=True)


def run_dssp(u, protein_sel, ligand_sel, system_name, out_dir):
    logging.info(f"Calculating Secondary Structure (DSSP) for {system_name}...")

    dssp_masks = {'Receptor': f'protein and {protein_sel}'}

    if ligand_sel:
        lig_atoms = u.select_atoms(ligand_sel)
        if len(lig_atoms.select_atoms("name CA")) > 0:
            dssp_masks['Ligand'] = ligand_sel
        else:
            logging.info(" -> Ligand appears to be a small molecule. Skipping DSSP for ligand.")

    for target_name, mask_string in dssp_masks.items():
        selection = u.select_atoms(mask_string)

        if len(selection) == 0:
            logging.info(f" -> Skipping {target_name}: No atoms found for mask '{mask_string}'.")
            continue

        dssp_calc   = dssp.DSSP(selection).run()
        combined_ss = dssp_calc.results.dssp
        total_frames = combined_ss.shape[0]

        # --- NEW: Save the RAW frame-by-frame letter data ---
        df_raw = pd.DataFrame(combined_ss, columns=selection.residues.resids)
        df_raw.index.name = 'Frame'
        df_raw.to_csv(out_dir / f"{system_name}_{target_name}_Raw_SS.csv")
        # ----------------------------------------------------

        helix_counts = np.isin(combined_ss, ['H', 'G', 'I']).sum(axis=0)
        sheet_counts = np.isin(combined_ss, ['E', 'B']).sum(axis=0)
        coil_counts  = total_frames - (helix_counts + sheet_counts)

        df_target = pd.DataFrame({'Residue': selection.residues.resids})
        df_target['Alpha Helix'] = (helix_counts / total_frames) * 100
        df_target['Beta Sheet']  = (sheet_counts / total_frames) * 100
        df_target['Coil']        = (coil_counts  / total_frames) * 100
        df_target.set_index('Residue', inplace=True)

        ss_cols    = ['Alpha Helix', 'Beta Sheet', 'Coil']
        max_vals   = df_target[ss_cols].max(axis=1)
        dominant   = df_target[ss_cols].idxmax(axis=1)
        df_target['Dominant_SS']  = np.where(max_vals >= 60.0, dominant, 'Mixed')
        df_target['Confidence_%'] = max_vals.round(2)

        # --- RENAMED: Output precisely matches the Jupyter pipeline ---
        out_file = out_dir / f"{system_name}_{target_name}_SS_Per_Res.csv"
        df_target.to_csv(out_file, index=True)
        logging.info(f" -> Saved {target_name} SS classifications to {out_file.name}")


def run_dihedrals(u, system_name, out_dir, motif_dry, motif_tswitch, motif_npy):
    logging.info(f"Calculating Micro-Switch Dihedrals (Chi-1) for {system_name}...")

    target_motifs = {}
    if motif_dry     is not None: target_motifs['Ionic_Lock_R']   = motif_dry
    if motif_tswitch is not None: target_motifs['Toggle_Switch_W'] = motif_tswitch
    if motif_npy     is not None: target_motifs['NPxxY_Y']         = motif_npy

    if not target_motifs:
        logging.info(" -> No motif residues provided. Skipping dihedral analysis.")
        return

    total_frames = len(u.trajectory)
    dt_ps = getattr(u.trajectory, 'dt', 10.0)

    sys_df = pd.DataFrame({
        'Frame':   np.arange(total_frames),
        'Time_ns': np.arange(total_frames) * (dt_ps / 1000.0)
    })

    for motif_name, res_id in target_motifs.items():
        res_atoms = u.select_atoms(f"resid {res_id}")
        if len(res_atoms) == 0:
            logging.warning(f" -> Residue {res_id} not found. Skipping {motif_name}.")
            continue

        resname = res_atoms.residues[0].resname.upper()
        cg_atom = CHI1_CG_MAP.get(resname, CHI1_DEFAULT_CG)
        logging.info(f" -> {motif_name} ({resname} {res_id}): Using Chi-1 atoms N-CA-CB-{cg_atom}")

        chi1_atom_names = ['N', 'CA', 'CB', cg_atom]
        atom_groups = [u.select_atoms(f"resid {res_id} and name {atom}") for atom in chi1_atom_names]

        if any(len(ag) == 0 for ag in atom_groups):
            logging.warning(f" -> Missing atoms for {motif_name} ({resname} {res_id}). Skipping.")
            continue

        target_dihedral_atoms = atom_groups[0] + atom_groups[1] + atom_groups[2] + atom_groups[3]
        dih_analysis = dihedrals.Dihedral([target_dihedral_atoms]).run()
        sys_df[motif_name] = dih_analysis.results.angles[:, 0]
        logging.info(f" -> {motif_name} (Residue {res_id}): Extracted {total_frames} frames.")

    sys_df.to_csv(out_dir / f"{system_name}_Dihedral_Chi1.csv", index=False)


def run_sasa(u, system_name, out_dir, sasa_resids):
    logging.info(f"Calculating SASA for {system_name}...")

    freesasa.setVerbosity(freesasa.nowarnings)

    res_str = " ".join(map(str, sasa_resids))
    pocket_sel = f"protein and resid {res_str}"

    # 1. Select the AtomGroup first
    pocket_ag = u.select_atoms(pocket_sel)

    if len(pocket_ag) == 0:
        logging.warning(" -> WARNING: No atoms found for SASA selection. Skipping.")
        return

    logging.info(f" -> Selected {len(pocket_ag)} atoms across {len(pocket_ag.residues)} residues.")

    sasa_calc = SASAAnalysis(pocket_ag).run(verbose=True)

    total_frames = len(u.trajectory)
    dt_ps = getattr(u.trajectory, 'dt', 10.0)

    try:
        sasa_data = sasa_calc.results.sasa
    except AttributeError:
        # Fallback for different mdakit_sasa versions
        sasa_data = sasa_calc.results.get('total_sasa', np.zeros(total_frames))

    # 4. Build and save the DataFrame
    sasa_df = pd.DataFrame({
        'Frame': np.arange(total_frames),
        'Time_ns': np.arange(total_frames) * (dt_ps / 1000.0),
        'SASA_A2': sasa_data
    })

    csv_path = out_dir / f"{system_name}_Intracellular_Pocket_SASA.csv"
    sasa_df.to_csv(csv_path, index=False)
    logging.info(f" -> SASA data successfully saved.")

def run_volume(u, system_name, top, traj_list, out_dir, vol_resids):
    logging.info(f"Calculating Cavity Volume (pyKVFinder) for {system_name}...")

    # REMOVED: Redundant on-the-fly alignment (ref and align_transform).
    # The trajectory (u) is already aligned in RAM because RMSF ran first.

    protein  = u.select_atoms("protein")
    vdw_dict = {'C': 1.70, 'O': 1.52, 'N': 1.55, 'S': 1.80, 'H': 1.20, 'P': 1.80}
    radii    = np.array([vdw_dict.get(atom.element.upper(), 1.50) for atom in protein])

    try:
        chains = protein.chainIDs
    except AttributeError:
        try:
            chains = protein.segids
        except AttributeError:
            chains = np.array(['A'] * len(protein))

    atomic_data = np.empty((len(protein), 8), dtype=object)
    atomic_data[:, 0] = protein.names
    atomic_data[:, 1] = protein.resnames
    atomic_data[:, 2] = chains
    atomic_data[:, 3] = protein.resids
    atomic_data[:, 7] = radii

    pocket_atoms = u.select_atoms(f"protein and resid {' '.join(map(str, vol_resids))}")
    if len(pocket_atoms) == 0:
        logging.warning(" -> WARNING: No atoms found for Volume selection. Skipping.")
        return

    u.trajectory[0]
    box_buffer = 5.0
    p_min = pocket_atoms.positions.min(axis=0) - box_buffer
    p_max = pocket_atoms.positions.max(axis=0) + box_buffer

    box_vertices = np.array([
        [p_min[0], p_min[1], p_min[2]],
        [p_max[0], p_min[1], p_min[2]],
        [p_min[0], p_max[1], p_min[2]],
        [p_min[0], p_min[1], p_max[2]]
    ])

    volumes   = []
    step_size = 0.6
    voxel_volume = step_size ** 3  # 0.216 Å³

    for ts in tqdm(u.trajectory, desc=f"Volume {system_name}"):
        atomic_data[:, 4:7] = protein.positions
        results = pyKVFinder.detect(
            atomic=atomic_data, vertices=box_vertices,
            step=step_size, probe_in=1.4, probe_out=4.0)

        num_cavities = results[0]
        grid         = results[1]

        if num_cavities > 0:
            cavity_volumes = [np.sum(grid == cav_id) * voxel_volume
                              for cav_id in range(1, num_cavities + 1)]
            volumes.append(max(cavity_volumes))
        else:
            volumes.append(0.0)

    total_frames = len(volumes)
    dt_ps = getattr(u.trajectory, 'dt', 10.0)

    pd.DataFrame({
        'Frame':     range(total_frames),
        'Time_ns':   [i * (dt_ps / 1000.0) for i in range(total_frames)],
        'Volume_A3': volumes
    }).to_csv(out_dir / f"{system_name}_Intracellular_Pocket_Volume.csv", index=False)

def run_intramolecular_frames(u, system_name, rep_num, target_sel_str,
                               tracked_interactions, out_dir, n_jobs):
    logging.info(f"[{system_name} Rep {rep_num}] Starting ProLIF Intramolecular extraction...")

    target_ag = u.select_atoms(target_sel_str)
    if len(target_ag) == 0:
        logging.warning(f"[{system_name} Rep {rep_num}] WARNING: "
                        f"Selection '{target_sel_str}' found 0 atoms. Skipping.")
        return False

    fp = plf.Fingerprint(tracked_interactions, vicinity_cutoff=5.0)
    fp = patch_prolif_intramolecular(fp)
    fp.run(u.trajectory, lig=target_ag, prot=target_ag, n_jobs=n_jobs)
    df_raw = fp.to_dataframe()

    raw_csv_path = out_dir / f"{system_name}_Rep{rep_num}_Raw_ProLIF.csv"
    df_raw.to_csv(raw_csv_path)
    logging.info(f"[{system_name} Rep {rep_num}] Saved raw ProLIF dataframe to {raw_csv_path.name}")
    logging.info(f"[{system_name} Rep {rep_num}] Writing {len(df_raw)} frames to disk...")

    frame_out_dir = out_dir / f"{system_name}_Rep{rep_num}_Frames"
    frame_out_dir.mkdir(parents=True, exist_ok=True)

    for frame_idx in df_raw.index:
        df_frame = df_raw.loc[[frame_idx]]
        df_t     = df_frame.T
        df_t.columns = ['Contact_Exists']
        df_plip  = df_t.unstack(level='interaction', fill_value=False)
        df_plip.columns = df_plip.columns.droplevel(0)
        df_plip.to_csv(frame_out_dir / f"Frame_{frame_idx:04d}.csv")

    logging.info(f"[{system_name} Rep {rep_num}] Frame extraction complete.")
    return True


def run_intermolecular_frames(u, system_name, rep_num, protein_sel_str,
                               ligand_sel_str, tracked_interactions, out_dir, n_jobs):
    logging.info(f"[{system_name} Rep {rep_num}] Starting ProLIF Intermolecular extraction...")

    protein_ag = u.select_atoms(protein_sel_str)
    ligand_ag  = u.select_atoms(ligand_sel_str)

    if len(ligand_ag) == 0:
        logging.warning(f"[{system_name} Rep {rep_num}] WARNING: Ligand selection found 0 atoms. Skipping.")
        return False

    fp = plf.Fingerprint(tracked_interactions, vicinity_cutoff=5.0)
    fp.run(u.trajectory, lig=ligand_ag, prot=protein_ag, n_jobs=n_jobs)
    df_raw = fp.to_dataframe()

    raw_csv_path = out_dir / f"{system_name}_Rep{rep_num}_Raw_Inter_ProLIF.csv"
    df_raw.to_csv(raw_csv_path)
    logging.info(f"[{system_name} Rep {rep_num}] Saved raw ProLIF dataframe to {raw_csv_path.name}")

    frame_out_dir = out_dir / f"{system_name}_Inter_Rep{rep_num}_Frames"
    frame_out_dir.mkdir(parents=True, exist_ok=True)

    for frame_idx in df_raw.index:
        df_frame = df_raw.loc[[frame_idx]]
        df_t     = df_frame.T
        df_t.columns = ['Contact_Exists']
        df_plip  = df_t.unstack(level='interaction', fill_value=False)
        df_plip.columns = df_plip.columns.droplevel(0)
        df_plip.to_csv(frame_out_dir / f"Frame_{frame_idx:04d}.csv")

    logging.info(f"[{system_name} Rep {rep_num}] Intermolecular frame extraction complete.")
    return True


def aggregate_network(system_name, frame_dirs, final_out_dir, active_ranges, mode='intra'):
    """
    Parameters
    ----------
    mode : 'intra'  →  Receptor–Receptor contact network
           'inter'  →  Ligand–Receptor contact network
    """
    logging.info(f"Starting {mode}-molecular data formatting for {system_name}...")

    domain_map = {
        res: dom
        for dom, (start, end) in active_ranges.items()
        for res in range(start, end + 1)
    }

    # 1. Aggregate replicate frame files into per-replicate frequency tables
    rep_summaries = []
    for rep_num, frame_dir in enumerate(frame_dirs, 1):
        csv_files    = sorted(list(frame_dir.glob("Frame_*.csv")))
        total_frames = len(csv_files)
        if total_frames == 0:
            continue

        rep_sum_df = None
        for file_path in csv_files:
            df_frame   = pd.read_csv(file_path, index_col=[0, 1]).astype(int)
            rep_sum_df = df_frame if rep_sum_df is None else rep_sum_df.add(df_frame, fill_value=0)

        rep_freq_df = (rep_sum_df / total_frames) * 100
        rep_freq_df['Replicate'] = rep_num
        rep_summaries.append(rep_freq_df)

    if not rep_summaries:
        logging.error("No ProLIF data was parsed. Skipping aggregation.")
        return

    # 2. Mean and std across replicates
    df_all_reps = pd.concat(rep_summaries)
    df_avg = (df_all_reps.drop(columns=['Replicate'])
              .groupby(['ligand', 'protein']).mean()
              .add_suffix('_Avg_%'))
    df_std = (df_all_reps.drop(columns=['Replicate'])
              .groupby(['ligand', 'protein']).std()
              .add_suffix('_Std_%'))
    df_final = pd.concat([df_avg, df_std], axis=1).fillna(0.0)

    # 3. Column naming and residue label cleanup — differs by mode
    if mode == 'intra':
        df_final.index.names = ['Receptor_Residue_1', 'Receptor_Residue_2']
        df_final.reset_index(inplace=True)
        for col in ['Receptor_Residue_1', 'Receptor_Residue_2']:
            df_final[col] = (df_final[col].astype(str)
                             .str.replace(r'\.0$', '', regex=True)
                             .str.replace(r'([A-Za-z]+)(\d+)', r'\1-\2', regex=True))
        id_vars   = ['Receptor_Residue_1', 'Receptor_Residue_2']
        res1_col  = 'Receptor_Residue_1'
        res2_col  = 'Receptor_Residue_2'
        out_suffix = 'Intra'
    else:
        df_final.index.names = ['Ligand_Residue', 'Receptor_Residue']
        df_final.reset_index(inplace=True)
        for col in ['Ligand_Residue', 'Receptor_Residue']:
            df_final[col] = (df_final[col].astype(str)
                             .str.replace(r'\.0$', '', regex=True)
                             .str.replace(r'([A-Za-z]+)(\d+)', r'\1-\2', regex=True))
        id_vars   = ['Ligand_Residue', 'Receptor_Residue']
        res1_col  = 'Ligand_Residue'
        res2_col  = 'Receptor_Residue'
        out_suffix = 'Inter'

    # 4. Melt to Cytoscape edge format
    interaction_cols = [col for col in df_final.columns if '_Avg_%' in col]
    df_melted = pd.melt(df_final, id_vars=id_vars, value_vars=interaction_cols,
                        var_name='Interaction_Type', value_name='Frequency_%')
    df_melted['Interaction_Type'] = df_melted['Interaction_Type'].str.replace('_Avg_%', '', regex=False)
    df_edges = df_melted[df_melted['Frequency_%'] > 0.0].copy()

    # 5. Topological domain mapping
    df_edges['Res1_Num'] = df_edges[res1_col].str.extract(r'(\d+)').astype(float).fillna(0).astype(int)
    df_edges['Res2_Num'] = df_edges[res2_col].str.extract(r'(\d+)').astype(float).fillna(0).astype(int)

    df_edges['Domain_1'] = ("Ligand" if mode == 'inter'
                            else df_edges['Res1_Num'].map(domain_map).fillna("Unknown"))
    df_edges['Domain_2'] = df_edges['Res2_Num'].map(domain_map).fillna("Unknown")

    df_edges['Res1_Num_Rev'] = df_edges['Res1_Num'] * -1
    df_edges['Res2_Num_Rev'] = df_edges['Res2_Num'] * -1
    df_edges.sort_values(by='Frequency_%', ascending=False, inplace=True)

    out_file = final_out_dir / f"{system_name}_{out_suffix}_Cytoscape_Edges.csv"
    df_edges.to_csv(out_file, index=False)
    logging.info(f" -> Cytoscape network successfully saved to {out_file}")


# =============================================================================
# Main
# =============================================================================

def main():

    parser = argparse.ArgumentParser(description="MD Analysis Pipeline for GPCRs", add_help=False)
    parser.add_argument("--system",         type=str, required=True,
                        help="System name identifier (e.g., 'AT1R')")
    parser.add_argument("--RMSD",           action="store_true",
                        help="Run RMSD analysis")
    parser.add_argument("--RMSF",           action="store_true",
                        help="Run RMSF analysis")
    parser.add_argument("--DSSP",           action="store_true",
                        help="Run secondary structure content analysis")
    parser.add_argument("--length",         type=int, required=True,
                        help="Receptor residue count")
    parser.add_argument("--ligand",         type=str,
                        help="Ligand selection string (e.g., 'resname LIG and resid 311')")
    parser.add_argument("--dihedrals",      action="store_true",
                        help="Run micro-switch Chi-1 dihedral analysis")
    parser.add_argument("--motif-all",      type=int, nargs=3,
                        metavar=('DRY', 'TSWITCH', 'NPY'),
                        help="All 3 motif resids: --motif-all 126 256 302")
    parser.add_argument("--motif-dry",      type=int,
                        help="Residue ID for DRY motif (TM3)")
    parser.add_argument("--motif-tswitch",  type=int,
                        help="Residue ID for Toggle Switch (TM6)")
    parser.add_argument("--motif-npy",      type=int,
                        help="Residue ID for NPxxY motif (TM7)")
    parser.add_argument("--sasa",           type=int, nargs='+',
                        help="Residue IDs for pocket SASA (e.g., --sasa 31 34 36 96)")
    parser.add_argument("--volume",         type=int, nargs='*',
                        help="Run pyKVFinder cavity volume. Accepts resid list; "
                             "falls back to --sasa residues if used with no numbers.")
    parser.add_argument("--system-complex", type=str,
                        help="Restrict run to a specific subfolder (e.g., 'A18')")
    parser.add_argument("--intra",          action="store_true",
                        help="Run intra-molecular ProLIF on the whole receptor")
    parser.add_argument("--intra-sel",      type=int, nargs='+',
                        help="Residue IDs for localized intramolecular ProLIF")
    parser.add_argument("--inter",          action="store_true",
                        help="Run intermolecular (Protein–Ligand) ProLIF")
    parser.add_argument("--custom-domains", type=str,
                        help="Path to a domain definition file (see CUSTOM_DOMAINS.txt)")
    parser.add_argument("--n-jobs",         type=int, default=4,
                        help="Parallel jobs for ProLIF analysis (default: 4)")
    parser.add_argument("-h", "--help",     action="store_true",
                        help="Show this help message and exit")
    args = parser.parse_args()
    if args.help:
        print(CUSTOM_HELP_TEXT)
        import sys
        sys.exit(0)

    # Default: run RMSD + RMSF + DSSP when no analysis flag is given
    if not (args.RMSD or args.RMSF or args.DSSP or args.dihedrals
            or args.sasa or args.volume is not None
            or args.intra or args.intra_sel or args.inter):
        args.RMSD = True
        args.RMSF = True
        args.DSSP = True

    # Motif residue resolution — --motif-all overrides individual flags
    motif_dry_res     = args.motif_dry
    motif_tswitch_res = args.motif_tswitch
    motif_npy_res     = args.motif_npy

    if args.motif_all:
        motif_dry_res, motif_tswitch_res, motif_npy_res = args.motif_all

    # Pathing
    base_path      = Path(args.system)
    general_system = base_path.name

    # Logging — dual output: file + terminal
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s | %(levelname)s | %(message)s',
        handlers=[
            logging.FileHandler(base_path / "analysis.log"),
            logging.StreamHandler()
        ]
    )
    logging.info(f"=== Starting GPCR MD Analysis Pipeline for {general_system} ===")
    logging.getLogger('MDAnalysis').setLevel(logging.ERROR)
    logging.getLogger('mdakit_sasa').setLevel(logging.CRITICAL)
    warnings.filterwarnings('ignore', category=UserWarning)
    # Domain map resolution
    active_ranges = {}
    if args.custom_domains:
        logging.info(f"Parsing custom domain boundaries from: {args.custom_domains}")
        with open(args.custom_domains, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip blanks, comment lines, and the header (no colon or header-only)
                if not line or ':' not in line:
                    continue
                dom_name, _, span = line.partition(':')
                dom_name = dom_name.strip()
                span     = span.strip()
                if not span:
                    # Empty range left in template → will show as "Unknown" in output
                    logging.warning(f" -> Domain '{dom_name}' has no range defined. "
                                    f"Residues in this region will be labelled 'Unknown'.")
                    continue
                start_str, _, end_str = span.partition('-')
                active_ranges[dom_name] = (int(start_str.strip()), int(end_str.strip()))
        logging.info(f" -> Loaded {len(active_ranges)} domain ranges: {list(active_ranges.keys())}")
    else:
        if "AT2R" in general_system.upper():
            active_ranges = DEFAULT_DOMAINS["AT2R"]
            logging.info("Domain map: AT2R (auto-detected)")
        elif "MAS" in general_system.upper():
            active_ranges = DEFAULT_DOMAINS["MAS1"]
            logging.info("Domain map: MAS1 (auto-detected)")
        else:
            active_ranges = DEFAULT_DOMAINS["AT1R"]
            logging.warning(f"System name '{general_system}' not recognized as AT2R or MAS1 — "
                            f"defaulting to AT1R domain map.")

    # -------------------------------------------------------------------------
    # Main loop — one iteration per ligand/complex subfolder
    # -------------------------------------------------------------------------
    for ligand_dir in base_path.iterdir():
        if not ligand_dir.is_dir():
            continue
        if args.system_complex and ligand_dir.name != args.system_complex:
            continue

        topology_search = list(ligand_dir.glob("*.prmtop"))
        if not topology_search:
            continue

        ligand_name      = ligand_dir.name
        topology_path    = topology_search[0]
        trajectory_files = sorted(list(ligand_dir.rglob("*.nc")))

        output_path = base_path / "DATA" / ligand_name
        output_path.mkdir(parents=True, exist_ok=True)

        logging.info("Initializing Virtual Concatenation...")
        u_concat     = mda.Universe(topology_path, *trajectory_files)
        total_frames = len(u_concat.trajectory)

        # --- Replicate boundary metadata ---
        replicate_boundaries_frames   = []
        replicate_boundaries_time_ns  = []
        current_frame_count = 0
        current_time_ps     = 0.0

        temp_u_first    = mda.Universe(topology_path, trajectory_files[0])
        detected_dt_ps  = temp_u_first.trajectory.dt
        logging.info(f"Detected Time Step (dt) from metadata: {detected_dt_ps} ps\n")
        del temp_u_first

        for traj in trajectory_files:
            temp_u = mda.Universe(topology_path, traj)
            frames  = len(temp_u.trajectory)
            dt_ps   = temp_u.trajectory.dt
            current_frame_count += frames
            current_time_ps     += frames * dt_ps
            replicate_boundaries_frames.append(current_frame_count)
            replicate_boundaries_time_ns.append(float(current_time_ps / 1000.0))
            del temp_u

        total_time_ns = current_time_ps / 1000.0

        logging.info(f'Processing {ligand_name} system.')
        logging.info(f"Linked {len(trajectory_files)} replicates.")
        logging.info(f"Total Frames: {total_frames}")
        logging.info(f"Total Simulated Time: {total_time_ns:.2f} ns")
        logging.info(f"Replicate Boundaries (Frames): {replicate_boundaries_frames[:-1]}")
        logging.info(f"Replicate Boundaries (Time in ns): {replicate_boundaries_time_ns[:-1]}")

        with open(output_path / f'{ligand_name}_metadata.txt', "w") as f:
            f.write(f'Linked {len(trajectory_files)} replicates.\n')
            f.write(f'Total Concatenated Frames: {total_frames}\n')
            f.write(f'Total Simulated Time: {total_time_ns:.2f} ns\n')
            f.write(f'Replicate Boundaries (Frames): {replicate_boundaries_frames[:-1]}\n')
            f.write(f'Replicate Boundaries (Time in ns): {replicate_boundaries_time_ns[:-1]}\n')

        # --- MANDATORY GLOBAL ALIGNMENT ---
        logging.info(f"[{ligand_dir.name}] Applying global alignment...")
        ref = mda.Universe(topology_path, trajectory_files[0])
        ref.trajectory[0] # Anchor to first frame
        align.AlignTraj(u_concat, ref, select="protein and backbone", in_memory=True).run()
        logging.info(f"[{ligand_dir.name}] Alignment complete.")
        # ---------------------------------------

        # --- Receptor and ligand selection strings ---
        all_protein_like = u_concat.select_atoms("protein")
        all_residues     = all_protein_like.residues

        protein_sel_str = ""
        ligand_sel_str  = None
        has_ligand      = False

        if len(all_residues) > args.length:
            has_ligand        = True
            receptor_residues = all_residues[:args.length]
            protein_sel_str   = f"resid {' '.join(map(str, receptor_residues.resids))}"

            if args.ligand:
                ligand_sel_str = args.ligand
            else:
                ligand_residues = all_residues[args.length:]
                ligand_sel_str  = f"resid {' '.join(map(str, ligand_residues.resids))}"
        else:
            protein_sel_str = f"resid {' '.join(map(str, all_residues.resids))}"
            if args.ligand:
                has_ligand     = True
                ligand_sel_str = args.ligand

        # --- Build the analysis queue ---
        # Each entry: (display_name, callable)
        # Failures are isolated — one broken analysis does not abort the rest.
        analysis_queue = []

        if args.RMSD:
            analysis_queue.append(('RMSD', lambda: run_rmsd(
                u_concat, protein_sel_str, ligand_sel_str, ligand_name,
                topology_path, trajectory_files, output_path)))

        if args.RMSF:
            analysis_queue.append(('RMSF', lambda: run_rmsf(
                u_concat, protein_sel_str, ligand_sel_str, ligand_name,
                topology_path, trajectory_files, output_path)))

        if args.DSSP:
            analysis_queue.append(('DSSP', lambda: run_dssp(
                u_concat, protein_sel_str, ligand_sel_str, ligand_name, output_path)))

        if args.dihedrals:
            analysis_queue.append(('Dihedrals', lambda: run_dihedrals(
                u_concat, ligand_name, output_path,
                motif_dry_res, motif_tswitch_res, motif_npy_res)))

        if args.sasa:
            analysis_queue.append(('SASA', lambda: run_sasa(
                u_concat, ligand_name, output_path, args.sasa)))

        if args.volume is not None:
            vol_resids = args.volume if len(args.volume) > 0 else args.sasa
            if not vol_resids:
                logging.error(f"[{ligand_name}] Volume skipped: no residues provided "
                              f"and --sasa was not used as fallback.")
            else:
                analysis_queue.append(('Volume', lambda: run_volume(
                    u_concat, ligand_name, topology_path,
                    trajectory_files, output_path, vol_resids)))

        if args.intra or args.intra_sel:
            def run_intra_block():
                if args.intra_sel:
                    res_str        = " ".join(map(str, args.intra_sel))
                    target_sel_str = f"protein and resid {res_str}"
                    logging.info(f"[{ligand_name}] Localized ProLIF on residues: {res_str}")
                else:
                    target_sel_str = f"protein and {protein_sel_str}"
                    logging.info(f"[{ligand_name}] Global ProLIF on entire receptor.")

                frame_dirs = []
                for i, traj_path in enumerate(trajectory_files):
                    rep_num = i + 1
                    temp_u  = mda.Universe(topology_path, traj_path)
                    success = run_intramolecular_frames(
                        temp_u, ligand_name, rep_num, target_sel_str,
                        PROLIF_INTERACTIONS, output_path, args.n_jobs)
                    if success:
                        frame_dirs.append(output_path / f"{ligand_name}_Rep{rep_num}_Frames")
                    del temp_u
                    gc.collect()

                if frame_dirs:
                    aggregate_network(ligand_name, frame_dirs, output_path,
                                      active_ranges, mode='intra')

            analysis_queue.append(('Intra-molecular ProLIF', run_intra_block))

        if args.inter:
            def run_inter_block():
                if not has_ligand:
                    logging.warning(f"[{ligand_name}] No ligand detected. "
                                    f"Skipping intermolecular analysis.")
                    return

                inter_frame_dirs = []
                for i, traj_path in enumerate(trajectory_files):
                    rep_num = i + 1
                    temp_u  = mda.Universe(topology_path, traj_path)
                    success = run_intermolecular_frames(
                        temp_u, ligand_name, rep_num,
                        f"protein and {protein_sel_str}", ligand_sel_str,
                        PROLIF_INTERACTIONS, output_path, args.n_jobs)
                    if success:
                        inter_frame_dirs.append(
                            output_path / f"{ligand_name}_Inter_Rep{rep_num}_Frames")
                    del temp_u
                    gc.collect()

                if inter_frame_dirs:
                    aggregate_network(ligand_name, inter_frame_dirs, output_path,
                                      active_ranges, mode='inter')

            analysis_queue.append(('Inter-molecular ProLIF', run_inter_block))

        # --- Execute the queue ---
        try:
            for analysis_name, analysis_fn in analysis_queue:
                try:
                    analysis_fn()
                except Exception as e:
                    logging.error(f"[{ligand_name}] {analysis_name} FAILED: {e}",
                                  exc_info=True)

            logging.info(f"[{ligand_name}] All queued analyses completed.")

        finally:
            # Always free the trajectory from RAM before the next iteration
            if 'u_concat' in locals():
                del u_concat
            gc.collect()
            logging.info(f"[{ligand_name}] Cleared trajectory from memory.\n")


if __name__ == "__main__":
    main()
